---
pre-commit:
  parallel: true
  jobs:
    - name: gofmt
      glob: "*.go"
      run: go fmt ./...
    - name: go test
      glob: "*.go"
      run: go test ./...
    - name: go lint
      glob: "*.go"
      run: golangci-lint run --fix
    - name: typos
      run: typos --config .typos.toml .
    - name: yamlfmt
      glob: "*.ya?ml"
      run: yamlfmt -conf .yamlfmt.yml .
